CREATE OR REPLACE EDITIONABLE PACKAGE "PLS_LOGGER" AS
 --   1.FATAL
 --   2.ERROR
 --   3.WARN
 --   4.INFO
 --   5.DEBUG
 --   6.TRACE
    FUNCTION LOG_ERROR (
        P_PROC_NAME IN VARCHAR2,
        P_DIAGNOSTIC_LEVEL IN VARCHAR2 DEFAULT 'ERROR',
        P_ADDITIONAL_PARAMETER IN VARCHAR2 DEFAULT NULL,
        P_REQUEST IN CLOB DEFAULT NULL,
        P_RESPONCE IN CLOB DEFAULT NULL
    ) RETURN NUMBER;

    PROCEDURE ADD_LOG_DETAILS (
        P_LOG_ID IN NUMBER,
        P_KEY IN VARCHAR2,
        P_VALUES IN VARCHAR2
    );

    PROCEDURE ADD_LOG_CLOB (
        P_LOG_ID IN NUMBER,
        P_REQUEST IN CLOB DEFAULT NULL,
        P_RESPONCE IN CLOB DEFAULT NULL
    );
END PLS_LOGGER;
/